# Generated by Django 2.2.7 on 2019-11-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_channel_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-publish_time']},
        ),
    ]
